
version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=supersecretkey
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --bind 0.0.0.0
volumes:
  mongo-data:
